[package]
name = "se_models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
console = "0.15.0"
device_query = "1.0.0"
#hecs = "0.7.6"
rust-code-analysis = "0.0.24"